# Generated by Django 2.0.6 on 2018-07-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(default='김민규', max_length=30),
            preserve_default=False,
        ),
    ]
