# Generated by Django 2.0.6 on 2018-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='regdata',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
