# Generated by Django 2.0.6 on 2018-07-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_regdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='regdata',
            new_name='regdate',
        ),
    ]
